<a href="https://www.kaggle.com/code/kmljts/fragrantica-analysis?scriptVersionId=312285940" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd

### Reading CSV

In [2]:
df = pd.read_csv(
        '/kaggle/input/datasets/olgagmiufana1/fragrantica-com-fragrance-dataset/fra_perfumes.csv'
        # '/kaggle/input/datasets/olgagmiufana1/fragrantica-com-fragrance-dataset/fra_cleaned.csv'
)

df

,Name,Gender,Rating Value,Rating Count,Main Accords,Perfumers,Description,url
0,9am Afnanfor women,for women,3.73,174,"['citrus', 'musky', 'woody', 'aromatic', 'warm...",[],9ambyAfnanis a fragrance for women. Top notes ...,https://www.fragrantica.com/perfume/Afnan/9am-...
1,9am Dive Afnanfor women and men,for women and men,4.29,842,"['fruity', 'woody', 'green', 'warm spicy', 'ar...",[],9am DivebyAfnanis a Aromatic Aquatic fragrance...,https://www.fragrantica.com/perfume/Afnan/9am-...
2,9am pour Femme Afnanfor women,for women,4.00,68,"['fruity', 'musky', 'amber', 'citrus', 'powder...",[],9am pour FemmebyAfnanis a Amber fragrance for ...,https://www.fragrantica.com/perfume/Afnan/9am-...
3,9pm Afnanfor men,for men,4.50,"6,865","['vanilla', 'amber', 'warm spicy', 'cinnamon',...",[],9pmbyAfnanis a Amber Vanilla fragrance for men...,https://www.fragrantica.com/perfume/Afnan/9pm-...
4,9pm pour Femme Afnanfor women,for women,3.49,63,"['woody', 'aromatic', 'rose', 'fruity', 'powde...",[],9pm pour FemmebyAfnanis a Amber Floral fragran...,https://www.fragrantica.com/perfume/Afnan/9pm-...
...,...,...,...,...,...,...,...,...
70098,Mystique Femme Al Haramain Perfumesfor women,for women,3.83,99,"['fruity', 'fresh', 'rose', 'floral', 'sweet',...",[],Mystique FemmebyAl Haramain Perfumesis a Flora...,https://www.fragrantica.com/perfume/Al-Haramai...
70099,Mirsaal of Trust Afnanfor men,for men,4.24,406,"['amber', 'woody', 'fruity', 'warm spicy', 'mu...",[],Mirsaal of TrustbyAfnanis a Amber Spicy fragra...,https://www.fragrantica.com/perfume/Afnan/Mirs...
70100,Atifa Noir Al Haramain Perfumesfor women,for women,4.02,47,"['amber', 'warm spicy', 'sweet', 'musky', 'car...",['Christian Carbonnel'],Atifa NoirbyAl Haramain Perfumesis a Amber Van...,https://www.fragrantica.com/perfume/Al-Haramai...
70101,Matar Al Hub Al Haramain Perfumesfor women and...,for women and men,4.02,52,"['rose', 'powdery', 'amber', 'woody', 'oud', '...",[],Matar Al HubbyAl Haramain Perfumesis a Amber f...,https://www.fragrantica.com/perfume/Al-Haramai...
70102,Classic Al Haramain Perfumesfor women,for women,3.90,10,"['sweet', 'woody', 'white floral', 'vanilla', ...",[],ClassicbyAl Haramain Perfumesis a Floral fragr...,https://www.fragrantica.com/perfume/Al-Haramai...

### Extracting Name and Brand from Description

In [3]:
df.Description

0        9ambyAfnanis a fragrance for women. Top notes ...
1        9am DivebyAfnanis a Aromatic Aquatic fragrance...
2        9am pour FemmebyAfnanis a Amber fragrance for ...
3        9pmbyAfnanis a Amber Vanilla fragrance for men...
4        9pm pour FemmebyAfnanis a Amber Floral fragran...
                               ...
70098    Mystique FemmebyAl Haramain Perfumesis a Flora...
70099    Mirsaal of TrustbyAfnanis a Amber Spicy fragra...
70100    Atifa NoirbyAl Haramain Perfumesis a Amber Van...
70101    Matar Al HubbyAl Haramain Perfumesis a Amber f...
70102    ClassicbyAl Haramain Perfumesis a Floral fragr...
Name: Description, Length: 70103, dtype: object

In [4]:
df[['Name', 'Brand']] = df.Description.str.extract(r'^(.*?)by(.*?)is ')

df[['Name', 'Brand']]

                   Name                 Brand
0                   9am                 Afnan
1              9am Dive                 Afnan
2        9am pour Femme                 Afnan
3                   9pm                 Afnan
4        9pm pour Femme                 Afnan
...                 ...                   ...
70098    Mystique Femme  Al Haramain Perfumes
70099  Mirsaal of Trust                 Afnan
70100        Atifa Noir  Al Haramain Perfumes
70101      Matar Al Hub  Al Haramain Perfumes
70102           Classic  Al Haramain Perfumes

[70103 rows x 2 columns]

In [5]:
df

,Name,Gender,Rating Value,Rating Count,Main Accords,Perfumers,Description,url,Brand
0,9am,for women,3.73,174,"['citrus', 'musky', 'woody', 'aromatic', 'warm...",[],9ambyAfnanis a fragrance for women. Top notes ...,https://www.fragrantica.com/perfume/Afnan/9am-...,Afnan
1,9am Dive,for women and men,4.29,842,"['fruity', 'woody', 'green', 'warm spicy', 'ar...",[],9am DivebyAfnanis a Aromatic Aquatic fragrance...,https://www.fragrantica.com/perfume/Afnan/9am-...,Afnan
2,9am pour Femme,for women,4.00,68,"['fruity', 'musky', 'amber', 'citrus', 'powder...",[],9am pour FemmebyAfnanis a Amber fragrance for ...,https://www.fragrantica.com/perfume/Afnan/9am-...,Afnan
3,9pm,for men,4.50,"6,865","['vanilla', 'amber', 'warm spicy', 'cinnamon',...",[],9pmbyAfnanis a Amber Vanilla fragrance for men...,https://www.fragrantica.com/perfume/Afnan/9pm-...,Afnan
4,9pm pour Femme,for women,3.49,63,"['woody', 'aromatic', 'rose', 'fruity', 'powde...",[],9pm pour FemmebyAfnanis a Amber Floral fragran...,https://www.fragrantica.com/perfume/Afnan/9pm-...,Afnan
...,...,...,...,...,...,...,...,...,...
70098,Mystique Femme,for women,3.83,99,"['fruity', 'fresh', 'rose', 'floral', 'sweet',...",[],Mystique FemmebyAl Haramain Perfumesis a Flora...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes
70099,Mirsaal of Trust,for men,4.24,406,"['amber', 'woody', 'fruity', 'warm spicy', 'mu...",[],Mirsaal of TrustbyAfnanis a Amber Spicy fragra...,https://www.fragrantica.com/perfume/Afnan/Mirs...,Afnan
70100,Atifa Noir,for women,4.02,47,"['amber', 'warm spicy', 'sweet', 'musky', 'car...",['Christian Carbonnel'],Atifa NoirbyAl Haramain Perfumesis a Amber Van...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes
70101,Matar Al Hub,for women and men,4.02,52,"['rose', 'powdery', 'amber', 'woody', 'oud', '...",[],Matar Al HubbyAl Haramain Perfumesis a Amber f...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes
70102,Classic,for women,3.90,10,"['sweet', 'woody', 'white floral', 'vanilla', ...",[],ClassicbyAl Haramain Perfumesis a Floral fragr...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes

### Fixing Gender

In [6]:
df.Gender.value_counts()

Gender
for women and men    29708
for women            28102
for men              12290
Name: count, dtype: int64

In [7]:
df.Gender = df.Gender.str.lower().map({
    'for men': 'M',
    'for women': 'F',
    'for women and men': 'U'
})

df.Gender

0        F
1        U
2        F
3        M
4        F
        ..
70098    F
70099    M
70100    F
70101    U
70102    F
Name: Gender, Length: 70103, dtype: object

In [8]:
df.Gender.value_counts()

Gender
U    29708
F    28102
M    12290
Name: count, dtype: int64

In [9]:
df

,Name,Gender,Rating Value,Rating Count,Main Accords,Perfumers,Description,url,Brand
0,9am,F,3.73,174,"['citrus', 'musky', 'woody', 'aromatic', 'warm...",[],9ambyAfnanis a fragrance for women. Top notes ...,https://www.fragrantica.com/perfume/Afnan/9am-...,Afnan
1,9am Dive,U,4.29,842,"['fruity', 'woody', 'green', 'warm spicy', 'ar...",[],9am DivebyAfnanis a Aromatic Aquatic fragrance...,https://www.fragrantica.com/perfume/Afnan/9am-...,Afnan
2,9am pour Femme,F,4.00,68,"['fruity', 'musky', 'amber', 'citrus', 'powder...",[],9am pour FemmebyAfnanis a Amber fragrance for ...,https://www.fragrantica.com/perfume/Afnan/9am-...,Afnan
3,9pm,M,4.50,"6,865","['vanilla', 'amber', 'warm spicy', 'cinnamon',...",[],9pmbyAfnanis a Amber Vanilla fragrance for men...,https://www.fragrantica.com/perfume/Afnan/9pm-...,Afnan
4,9pm pour Femme,F,3.49,63,"['woody', 'aromatic', 'rose', 'fruity', 'powde...",[],9pm pour FemmebyAfnanis a Amber Floral fragran...,https://www.fragrantica.com/perfume/Afnan/9pm-...,Afnan
...,...,...,...,...,...,...,...,...,...
70098,Mystique Femme,F,3.83,99,"['fruity', 'fresh', 'rose', 'floral', 'sweet',...",[],Mystique FemmebyAl Haramain Perfumesis a Flora...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes
70099,Mirsaal of Trust,M,4.24,406,"['amber', 'woody', 'fruity', 'warm spicy', 'mu...",[],Mirsaal of TrustbyAfnanis a Amber Spicy fragra...,https://www.fragrantica.com/perfume/Afnan/Mirs...,Afnan
70100,Atifa Noir,F,4.02,47,"['amber', 'warm spicy', 'sweet', 'musky', 'car...",['Christian Carbonnel'],Atifa NoirbyAl Haramain Perfumesis a Amber Van...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes
70101,Matar Al Hub,U,4.02,52,"['rose', 'powdery', 'amber', 'woody', 'oud', '...",[],Matar Al HubbyAl Haramain Perfumesis a Amber f...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes
70102,Classic,F,3.90,10,"['sweet', 'woody', 'white floral', 'vanilla', ...",[],ClassicbyAl Haramain Perfumesis a Floral fragr...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes

In [10]:
df

,Name,Gender,Rating Value,Rating Count,Main Accords,Perfumers,Description,url,Brand
0,9am,F,3.73,174,"['citrus', 'musky', 'woody', 'aromatic', 'warm...",[],9ambyAfnanis a fragrance for women. Top notes ...,https://www.fragrantica.com/perfume/Afnan/9am-...,Afnan
1,9am Dive,U,4.29,842,"['fruity', 'woody', 'green', 'warm spicy', 'ar...",[],9am DivebyAfnanis a Aromatic Aquatic fragrance...,https://www.fragrantica.com/perfume/Afnan/9am-...,Afnan
2,9am pour Femme,F,4.00,68,"['fruity', 'musky', 'amber', 'citrus', 'powder...",[],9am pour FemmebyAfnanis a Amber fragrance for ...,https://www.fragrantica.com/perfume/Afnan/9am-...,Afnan
3,9pm,M,4.50,"6,865","['vanilla', 'amber', 'warm spicy', 'cinnamon',...",[],9pmbyAfnanis a Amber Vanilla fragrance for men...,https://www.fragrantica.com/perfume/Afnan/9pm-...,Afnan
4,9pm pour Femme,F,3.49,63,"['woody', 'aromatic', 'rose', 'fruity', 'powde...",[],9pm pour FemmebyAfnanis a Amber Floral fragran...,https://www.fragrantica.com/perfume/Afnan/9pm-...,Afnan
...,...,...,...,...,...,...,...,...,...
70098,Mystique Femme,F,3.83,99,"['fruity', 'fresh', 'rose', 'floral', 'sweet',...",[],Mystique FemmebyAl Haramain Perfumesis a Flora...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes
70099,Mirsaal of Trust,M,4.24,406,"['amber', 'woody', 'fruity', 'warm spicy', 'mu...",[],Mirsaal of TrustbyAfnanis a Amber Spicy fragra...,https://www.fragrantica.com/perfume/Afnan/Mirs...,Afnan
70100,Atifa Noir,F,4.02,47,"['amber', 'warm spicy', 'sweet', 'musky', 'car...",['Christian Carbonnel'],Atifa NoirbyAl Haramain Perfumesis a Amber Van...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes
70101,Matar Al Hub,U,4.02,52,"['rose', 'powdery', 'amber', 'woody', 'oud', '...",[],Matar Al HubbyAl Haramain Perfumesis a Amber f...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes
70102,Classic,F,3.90,10,"['sweet', 'woody', 'white floral', 'vanilla', ...",[],ClassicbyAl Haramain Perfumesis a Floral fragr...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes

### Converting `Rating Count` to `Int64`

In [11]:
df['Rating Count'] = (
    df['Rating Count']
    .str.replace(',', '')
    .astype(float)
    .astype('Int64')
)

In [12]:
df.dtypes

Name             object
Gender           object
Rating Value    float64
Rating Count      Int64
Main Accords     object
Perfumers        object
Description      object
url              object
Brand            object
dtype: object

In [13]:
df

,Name,Gender,Rating Value,Rating Count,Main Accords,Perfumers,Description,url,Brand
0,9am,F,3.73,174,"['citrus', 'musky', 'woody', 'aromatic', 'warm...",[],9ambyAfnanis a fragrance for women. Top notes ...,https://www.fragrantica.com/perfume/Afnan/9am-...,Afnan
1,9am Dive,U,4.29,842,"['fruity', 'woody', 'green', 'warm spicy', 'ar...",[],9am DivebyAfnanis a Aromatic Aquatic fragrance...,https://www.fragrantica.com/perfume/Afnan/9am-...,Afnan
2,9am pour Femme,F,4.00,68,"['fruity', 'musky', 'amber', 'citrus', 'powder...",[],9am pour FemmebyAfnanis a Amber fragrance for ...,https://www.fragrantica.com/perfume/Afnan/9am-...,Afnan
3,9pm,M,4.50,6865,"['vanilla', 'amber', 'warm spicy', 'cinnamon',...",[],9pmbyAfnanis a Amber Vanilla fragrance for men...,https://www.fragrantica.com/perfume/Afnan/9pm-...,Afnan
4,9pm pour Femme,F,3.49,63,"['woody', 'aromatic', 'rose', 'fruity', 'powde...",[],9pm pour FemmebyAfnanis a Amber Floral fragran...,https://www.fragrantica.com/perfume/Afnan/9pm-...,Afnan
...,...,...,...,...,...,...,...,...,...
70098,Mystique Femme,F,3.83,99,"['fruity', 'fresh', 'rose', 'floral', 'sweet',...",[],Mystique FemmebyAl Haramain Perfumesis a Flora...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes
70099,Mirsaal of Trust,M,4.24,406,"['amber', 'woody', 'fruity', 'warm spicy', 'mu...",[],Mirsaal of TrustbyAfnanis a Amber Spicy fragra...,https://www.fragrantica.com/perfume/Afnan/Mirs...,Afnan
70100,Atifa Noir,F,4.02,47,"['amber', 'warm spicy', 'sweet', 'musky', 'car...",['Christian Carbonnel'],Atifa NoirbyAl Haramain Perfumesis a Amber Van...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes
70101,Matar Al Hub,U,4.02,52,"['rose', 'powdery', 'amber', 'woody', 'oud', '...",[],Matar Al HubbyAl Haramain Perfumesis a Amber f...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes
70102,Classic,F,3.90,10,"['sweet', 'woody', 'white floral', 'vanilla', ...",[],ClassicbyAl Haramain Perfumesis a Floral fragr...,https://www.fragrantica.com/perfume/Al-Haramai...,Al Haramain Perfumes

### Filtering Columns

In [14]:
df = df[['Brand', 'Name', 'Gender', 'Rating Value', 'Rating Count', 'Main Accords', 'url']]

df

,Brand,Name,Gender,Rating Value,Rating Count,Main Accords,url
0,Afnan,9am,F,3.73,174,"['citrus', 'musky', 'woody', 'aromatic', 'warm...",https://www.fragrantica.com/perfume/Afnan/9am-...
1,Afnan,9am Dive,U,4.29,842,"['fruity', 'woody', 'green', 'warm spicy', 'ar...",https://www.fragrantica.com/perfume/Afnan/9am-...
2,Afnan,9am pour Femme,F,4.00,68,"['fruity', 'musky', 'amber', 'citrus', 'powder...",https://www.fragrantica.com/perfume/Afnan/9am-...
3,Afnan,9pm,M,4.50,6865,"['vanilla', 'amber', 'warm spicy', 'cinnamon',...",https://www.fragrantica.com/perfume/Afnan/9pm-...
4,Afnan,9pm pour Femme,F,3.49,63,"['woody', 'aromatic', 'rose', 'fruity', 'powde...",https://www.fragrantica.com/perfume/Afnan/9pm-...
...,...,...,...,...,...,...,...
70098,Al Haramain Perfumes,Mystique Femme,F,3.83,99,"['fruity', 'fresh', 'rose', 'floral', 'sweet',...",https://www.fragrantica.com/perfume/Al-Haramai...
70099,Afnan,Mirsaal of Trust,M,4.24,406,"['amber', 'woody', 'fruity', 'warm spicy', 'mu...",https://www.fragrantica.com/perfume/Afnan/Mirs...
70100,Al Haramain Perfumes,Atifa Noir,F,4.02,47,"['amber', 'warm spicy', 'sweet', 'musky', 'car...",https://www.fragrantica.com/perfume/Al-Haramai...
70101,Al Haramain Perfumes,Matar Al Hub,U,4.02,52,"['rose', 'powdery', 'amber', 'woody', 'oud', '...",https://www.fragrantica.com/perfume/Al-Haramai...
70102,Al Haramain Perfumes,Classic,F,3.90,10,"['sweet', 'woody', 'white floral', 'vanilla', ...",https://www.fragrantica.com/perfume/Al-Haramai...

In [15]:
df.columns = ['brand', 'name', 'gender', 'rating_value', 'rating_count', 'main_accords', 'url']

df.columns

Index(['brand', 'name', 'gender', 'rating_value', 'rating_count',
       'main_accords', 'url'],
      dtype='object')

In [16]:
df

,brand,name,gender,rating_value,rating_count,main_accords,url
0,Afnan,9am,F,3.73,174,"['citrus', 'musky', 'woody', 'aromatic', 'warm...",https://www.fragrantica.com/perfume/Afnan/9am-...
1,Afnan,9am Dive,U,4.29,842,"['fruity', 'woody', 'green', 'warm spicy', 'ar...",https://www.fragrantica.com/perfume/Afnan/9am-...
2,Afnan,9am pour Femme,F,4.00,68,"['fruity', 'musky', 'amber', 'citrus', 'powder...",https://www.fragrantica.com/perfume/Afnan/9am-...
3,Afnan,9pm,M,4.50,6865,"['vanilla', 'amber', 'warm spicy', 'cinnamon',...",https://www.fragrantica.com/perfume/Afnan/9pm-...
4,Afnan,9pm pour Femme,F,3.49,63,"['woody', 'aromatic', 'rose', 'fruity', 'powde...",https://www.fragrantica.com/perfume/Afnan/9pm-...
...,...,...,...,...,...,...,...
70098,Al Haramain Perfumes,Mystique Femme,F,3.83,99,"['fruity', 'fresh', 'rose', 'floral', 'sweet',...",https://www.fragrantica.com/perfume/Al-Haramai...
70099,Afnan,Mirsaal of Trust,M,4.24,406,"['amber', 'woody', 'fruity', 'warm spicy', 'mu...",https://www.fragrantica.com/perfume/Afnan/Mirs...
70100,Al Haramain Perfumes,Atifa Noir,F,4.02,47,"['amber', 'warm spicy', 'sweet', 'musky', 'car...",https://www.fragrantica.com/perfume/Al-Haramai...
70101,Al Haramain Perfumes,Matar Al Hub,U,4.02,52,"['rose', 'powdery', 'amber', 'woody', 'oud', '...",https://www.fragrantica.com/perfume/Al-Haramai...
70102,Al Haramain Perfumes,Classic,F,3.90,10,"['sweet', 'woody', 'white floral', 'vanilla', ...",https://www.fragrantica.com/perfume/Al-Haramai...

### Handling NULLs

In [17]:
df.isna().sum()

brand              3
name               3
gender             3
rating_value    6181
rating_count    6181
main_accords       0
url                0
dtype: int64

In [18]:
df = df.dropna(subset=['brand'])

df.isna().sum()

brand              0
name               0
gender             0
rating_value    6178
rating_count    6178
main_accords       0
url                0
dtype: int64

In [19]:
df[df.rating_value.isna()]

,brand,name,gender,rating_value,rating_count,main_accords,url
9,Afnan,Afzal Abeer,F,NaN,<NA>,[],https://www.fragrantica.com/perfume/Afnan/Afza...
191,Al Haramain Perfumes,Amber Sanitizer,U,NaN,<NA>,"['musky', 'iris', 'warm spicy', 'powdery', 'me...",https://www.fragrantica.com/perfume/Al-Haramai...
192,Al Haramain Perfumes,Musk Sanitizer,U,NaN,<NA>,"['musky', 'powdery']",https://www.fragrantica.com/perfume/Al-Haramai...
193,Al Haramain Perfumes,Oudi Sanitizer,U,NaN,<NA>,"['amber', 'woody', 'musky', 'smoky', 'sweet', ...",https://www.fragrantica.com/perfume/Al-Haramai...
228,Al-Rehab,CHE BELLA,F,NaN,<NA>,"['fruity', 'white floral', 'sweet', 'musky', '...",https://www.fragrantica.com/perfume/Al-Rehab/C...
...,...,...,...,...,...,...,...
70075,Otoori,Night Attitude,U,NaN,<NA>,"['sweet', 'fruity', 'citrus', 'floral', 'musky...",https://www.fragrantica.com/perfume/Otoori/Nig...
70080,Otoori,Unleashed,U,NaN,<NA>,"['woody', 'aromatic', 'fresh spicy', 'fruity',...",https://www.fragrantica.com/perfume/Otoori/Unl...
70094,Parfums Genty,Delicata Lilla,F,NaN,<NA>,"['floral', 'fresh', 'musky', 'green', 'powdery']",https://www.fragrantica.com/perfume/Parfums-Ge...
70095,Ed Pinaud,Florale Attraction,U,NaN,<NA>,"['floral', 'fruity', 'rose', 'powdery', 'viole...",https://www.fragrantica.com/perfume/Ed-Pinaud/...
70097,Otoori,Saffron,U,NaN,<NA>,"['woody', 'mossy', 'musky', 'earthy', 'floral'...",https://www.fragrantica.com/perfume/Otoori/Saf...

In [20]:
df[['rating_value', 'rating_count']] = df[['rating_value', 'rating_count']].fillna(0)

df.isna().sum()

/tmp/ipykernel_16/727314854.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['rating_value', 'rating_count']] = df[['rating_value', 'rating_count']].fillna(0)

brand           0
name            0
gender          0
rating_value    0
rating_count    0
main_accords    0
url             0
dtype: int64

### Finally, ANALYSIS!

In [21]:
df = df.iloc[:, :5]

df

,brand,name,gender,rating_value,rating_count
0,Afnan,9am,F,3.73,174
1,Afnan,9am Dive,U,4.29,842
2,Afnan,9am pour Femme,F,4.00,68
3,Afnan,9pm,M,4.50,6865
4,Afnan,9pm pour Femme,F,3.49,63
...,...,...,...,...,...
70098,Al Haramain Perfumes,Mystique Femme,F,3.83,99
70099,Afnan,Mirsaal of Trust,M,4.24,406
70100,Al Haramain Perfumes,Atifa Noir,F,4.02,47
70101,Al Haramain Perfumes,Matar Al Hub,U,4.02,52
70102,Al Haramain Perfumes,Classic,F,3.90,10

In [22]:
(
    df[(df.rating_count > 1000) & (df.gender != 'F')]
        .sort_values('rating_value', ascending=False)
        .head(30)
)

,brand,name,gender,rating_value,rating_count
8563,Jean Paul Gaultier,Le Male Le Parfum,M,4.60,13406
2086,Azzaro,The Most Wanted Parfum,M,4.59,3842
6407,Giorgio Armani,Emporio Armani Stronger With You Intensely,M,4.57,9587
2084,Azzaro,The Most Wanted,M,4.57,4897
13798,Roja Dove,Enigma Pour Homme,M,4.56,1674
8557,Jean Paul Gaultier,Le Male Elixir,M,4.56,10388
8535,Jean Paul Gaultier,Le Beau Le Parfum,M,4.56,7651
16607,Yves Saint Laurent,La Nuit de L'Homme Bleu Électrique,M,4.56,4228
10274,Lou,Imagination,M,4.55,2923
5288,Dior,Dior Homme Parfum,M,4.55,7676
3950,Chanel,Allure Homme Edition Blanche Eau de Parfum,M,4.54,3329
5283,Dior,Dior Homme Cologne 2022,M,4.53,2185
16120,Xerjoff,Torino21,U,4.53,2368
530,Armaf,Club de Nuit Intense Man Limited Edition Parfum,M,4.53,1476
14972,Valentino,Valentino Uomo Born In Roma Intense,M,4.52,3328
14970,Valentino,Valentino Uomo Born In Roma Coral Fantasy,M,4.52,2948
16010,Viktor&Rolf,Spicebomb Extreme,M,4.52,10644
45935,Tauer Perfumes,Au Coeur du Désert,U,4.51,2096
6404,Giorgio Armani,Emporio Armani Stronger With You Absolutely,M,4.51,4379
16222,Xerjoff,XJ 1861 Naxos,U,4.51,9969
13177,Prada,Prada L'Homme Intense,M,4.51,4326
8371,Issey Miyake,L'Eau d'Issey Pour Homme Noir Ambre,M,4.50,1044
3,Afnan,9pm,M,4.50,6865
41833,Mercedes-Benz,Mercedes Benz Club Black,M,4.50,3693
5286,Dior,Dior Homme Intense 2011,M,4.50,18272
9741,Lattafa Perfumes,Khamrah Qahwa,U,4.49,1564
5662,Dolce&Gabbana,The One for Men Eau de Parfum,M,4.49,11353
12925,Paco Rabanne,Invictus Victory Elixir,M,4.48,2455
5285,Dior,Dior Homme Intense 2007,M,4.48,3446
7778,Guerlain,L'Instant de Guerlain pour Homme EDP,M,4.48,1376

In [23]:
(
    df[
        (True)
        & (df.brand == 'Lattafa Perfumes') 
        & (df.rating_count > 1000) 
        & (df.gender != 'F')
    ]
    .sort_values('rating_value', ascending=False)
    .head(30)
)

,brand,name,gender,rating_value,rating_count
9741,Lattafa Perfumes,Khamrah Qahwa,U,4.49,1564
9683,Lattafa Perfumes,Ramz Lattafa Silver,U,4.41,1131
9740,Lattafa Perfumes,Khamrah,U,4.39,9276
9729,Lattafa Perfumes,Bade'e Al Oud Honor & Glory,U,4.31,1487
9675,Lattafa Perfumes,Qaed Al Fursan,U,4.31,2767
9771,Lattafa Perfumes,Nebras,U,4.31,1725
9732,Lattafa Perfumes,Fakhar Black,M,4.28,2461
9726,Lattafa Perfumes,Asad,M,4.28,5345
9784,Lattafa Perfumes,Maahir Legacy,M,4.27,1153
9618,Lattafa Perfumes,Ameer Al Oudh Intense Oud,U,4.25,2886
9760,Lattafa Perfumes,Eternal Oud,U,4.24,1065
9730,Lattafa Perfumes,Bade'e Al Oud Oud for Glory,U,4.19,4222
9672,Lattafa Perfumes,Qaa'ed,U,4.17,1507
9708,Lattafa Perfumes,Velvet Oud,U,4.17,1111
9796,Lattafa Perfumes,Raghba Wood Intense,M,4.14,1366
9728,Lattafa Perfumes,Bade'e Al Oud Amethyst,U,4.11,1684
9666,Lattafa Perfumes,Oud Mood,U,4.05,1403
9724,Lattafa Perfumes,Ana Abiyedh Rouge,U,4.04,1623
9792,Lattafa Perfumes,Raghba,U,3.93,3243
9676,Lattafa Perfumes,Qaed Al Fursan Unlimited,U,3.91,1133
9722,Lattafa Perfumes,Ana Abiyedh,U,3.89,1371